<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotSpatial.Data" Version="4.0.656" />
    <PackageReference Include="DotSpatial.Projections" Version="4.0.656" />
    <PackageReference Include="DotSpatial.Serialization" Version="4.0.656" />
    <PackageReference Include="DotSpatial.Symbology" Version="4.0.656" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
