<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>assets\images\AugGISIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.OpenGL3" Version="1.1.0" />
    <PackageReference Include="Hexa.NET.SDL3" Version="1.2.16" />
    <PackageReference Include="Hexa.NET.SDL3.Image" Version="1.0.0" />
    <PackageReference Include="Hexa.NET.Utilities" Version="2.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AugGISDataParser\AugGISDataParser.csproj" />
    <ProjectReference Include="..\AugGISServerLauncher\AugGISServerLauncher.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DotSpatial.Data.Rasters.GdalExtension">
      <HintPath>..\Extensions\DotSpatial.Data.Rasters.GdalExtension\DotSpatial.Data.Rasters.GdalExtension.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(SolutionDir)Extensions\DotSpatial.Data.Rasters.GdalExtension\gdal\*.*&quot; &quot;$(TargetDir)gdal\&quot; /y /s /e&#xA;xcopy &quot;$(ProjectDir)assets&quot; &quot;$(TargetDir)assets&quot; /y /i /e" />
  </Target>

</Project>
